"""initial migration 2

Revision ID: 70f233c74e1d
Revises: 
Create Date: 2024-06-16 23:35:55.536269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f233c74e1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=True),
    sa.Column('deporte', sa.Enum('futbol', 'basket', 'voley', name='deporte'), nullable=False),
    sa.Column('colegio', sa.String(length=50), nullable=False),
    sa.Column('nombre_encargado', sa.String(length=30), nullable=False),
    sa.Column('telefono_encargado', sa.String(length=15), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('DNI', sa.String(length=8), nullable=False),
    sa.Column('celiaco', sa.Boolean(), nullable=True),
    sa.Column('vegano', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('DNI'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('partido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.Column('cancha', sa.Integer(), nullable=False),
    sa.Column('equipo1_id', sa.Integer(), nullable=False),
    sa.Column('equipo2_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['equipo1_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['equipo2_id'], ['equipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partido')
    op.drop_table('integrante')
    op.drop_table('equipo')
    # ### end Alembic commands ###
