"""Quitando atributo unique, causa restricciones

Revision ID: 9a95468e0974
Revises: d4f351e58bfa
Create Date: 2024-06-25 20:05:08.100550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a95468e0974'
down_revision = 'd4f351e58bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrante', schema=None) as batch_op:
        batch_op.drop_index('DNI')
        batch_op.drop_index('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrante', schema=None) as batch_op:
        batch_op.create_index('telefono', ['telefono'], unique=True)
        batch_op.create_index('DNI', ['DNI'], unique=True)

    # ### end Alembic commands ###
