"""Restructura de realcion equipo/partido

Revision ID: f201aafef026
Revises: 076ab2882376
Create Date: 2024-06-22 13:15:17.805580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f201aafef026'
down_revision = '076ab2882376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidos_equipos',
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partido.id'], ),
    sa.PrimaryKeyConstraint('partido_id', 'equipo_id')
    )
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.drop_constraint('partido_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('partido_ibfk_2', type_='foreignkey')
        batch_op.drop_column('equipo1_id')
        batch_op.drop_column('equipo2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo2_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('equipo1_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('partido_ibfk_2', 'equipo', ['equipo2_id'], ['id'])
        batch_op.create_foreign_key('partido_ibfk_1', 'equipo', ['equipo1_id'], ['id'])

    op.drop_table('partidos_equipos')
    # ### end Alembic commands ###
